version: '3'

services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/completeBariNginx/project:/var/www/completebari
      - /home/borgespatisserie/project:/var/www/borgespatisserie
      - ./certs:/etc/ssl
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - borgespatisserie_app-network
      - completebaringinx_complete-bari-network-nginx
networks:
  borgespatisserie_app-network:
    external: true
  completebaringinx_complete-bari-network-nginx:
    external: true
