version: '3'

services:
  webserver:
    image: nginx:alpine
    container_name: webserver-tests
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/borgerpatsserie/project:/var/www
      - ./certs:/etc/ssl
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - borgerpatsserie_app-network

networks:
  borgerpatsserie_app-network:
    external: true
